[project]
name = "gridworks-scada-protocol"
version = "1.1.1"
description = "Data structures used in messages between gridworks-scada devices, the gridworks ATN and the gridworks-admin monitoring CLI."
readme = "README.md"
authors = [
    { name = "Jessica Millar", email = "jmillar@gridworks-consulting.com" }
]
homepage = "https://github.com/thegridelectric/gridworks-scada/tree/dev/packages/gridworks-scada-protocol"
repository = "https://github.com/thegridelectric/gridworks-scada/tree/dev/packages/gridworks-scada-protocol"
requires-python = ">=3.11"
dependencies = [
    "gridworks-protocol>=1.3.3,<2.0.0",
    "transitions>=0.9.3",
]

[tool.uv.build-backend]
module-name = "gwsproto"

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"
