[project]
name = "gridworks-scada-protocol"
version = "1.0.0.dev1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jessica Millar", email = "jmillar@gridworks-consulting.com" }
]
requires-python = ">=3.11"
dependencies = [
    "gridworks-protocol>=1.2.9",
    "transitions>=0.9.3",
]

[tool.uv.build-backend]
module-name = "gwsproto"

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"
